"""Data to be saved in the player's file system/browser LocalStorage."""


class PlayerData:
    """Class containing persistent data generated by player action. Pickle instances to save them."""

    def __init__(self):
        pass
